# Generated by Django 4.2.3 on 2023-11-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gibi',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gibi_company', to='gibis.company'),
            preserve_default=False,
        ),
    ]
