# Generated by Django 4.2.3 on 2023-11-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibis', '0003_genre_alter_gibi_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gibi',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
