# Generated by Django 4.2.3 on 2023-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibis', '0004_gibi_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gibi',
            name='authors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gibi',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gibi',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
